version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres-devops
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  project-devops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-devops
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/todo
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  pgdata:
