apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: project-devops
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS todos (
      id SERIAL PRIMARY KEY,
      title VARCHAR(255) NOT NULL
    );
