apiVersion: v1
kind: Service
metadata:
  name: project-devops-service
  namespace: project-devops
spec:
  selector:
    app: project-devops
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  type: NodePort
